---

kind: pipeline
type: docker
name: default

steps:
- name: nosetests
  image: docker:19.03-dind
  when:
    event:
    - push
    - tag
  volumes:
  - name: docker_socket
    path: /var/run
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  commands:
  - >-
    (t=0; T=5; while ! docker info -f '{{.ID}}' 2>/dev/null; do t=$(( t + 1 )); test ${t} -ne ${T}; sleep 1; done)
  - docker build . -f testing.dockerfile --build-arg VERSION=${DRONE_COMMIT} -t opertusmundi/transform:${DRONE_COMMIT}-testing
  - docker run --rm -u 1000:1000 -v $PWD:/work -w /work opertusmundi/transform:${DRONE_COMMIT}-testing nosetests -v

services:
- name: docker
  image: docker:19.03-dind
  privileged: true
  volumes:
  - name: docker_socket
    path: /var/run

volumes:
- name: docker_socket
  temp: {}

