---

kind: pipeline
type: docker
name: default

steps:
- name: nosetests
  image: docker:19.03-dind
  when:
    event:
    - push
    - tag
  volumes:
  - name: docker_socket
    path: /var/run
  environment:
    DOCKER_HOST: unix:///var/run/docker.sock
  commands:
  - export image=opertusmundi/transform:${DRONE_COMMIT}-testing
  - (t=10; while ! docker info -f '{{.ID}}' 2>/dev/null; do t=$((t - 1)); test $${t} -ne 0; sleep 1; done)
  - docker build . -f testing.dockerfile --build-arg VERSION=${DRONE_COMMIT} -t $${image}
  - mkdir output data temp && chown -v 1000:1000 output data temp
  - export env_file=nosetests-${CI_BUILD_NUMBER}.env
  - >-
    (env -i
    TEMPDIR=/work/temp
    OUTPUT_DIR=/work/output
    INSTANCE_PATH=/work/data
    DATABASE=/work/data/transform-testing.sqlite
    ) | tee $${env_file}
  - docker run --rm -u 1000:1000 -v $PWD:/work -w /work --env-file $${env_file} $${image}

services:
- name: docker
  image: docker:19.03-dind
  privileged: true
  volumes:
  - name: docker_socket
    path: /var/run

volumes:
- name: docker_socket
  temp: {}

